// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3ittMwwukoAo2gr8tKclmSeqyQd0VW0',
    appId: '1:369587275430:web:06e5eaf6a61b935a931667',
    messagingSenderId: '369587275430',
    projectId: 'prak-mobile2025',
    authDomain: 'prak-mobile2025.firebaseapp.com',
    databaseURL: 'https://prak-mobile2025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prak-mobile2025.firebasestorage.app',
    measurementId: 'G-V057JMQP50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUHKVmvNhi9KtKiV_jfMuiFoRAx_TyCA',
    appId: '1:369587275430:android:2017c806a6894685931667',
    messagingSenderId: '369587275430',
    projectId: 'prak-mobile2025',
    databaseURL: 'https://prak-mobile2025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prak-mobile2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVAkZs8AhU_PWbT2jrYrUNHTarK4fT6Bg',
    appId: '1:369587275430:ios:e2cc9c713cbcde96931667',
    messagingSenderId: '369587275430',
    projectId: 'prak-mobile2025',
    databaseURL: 'https://prak-mobile2025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prak-mobile2025.firebasestorage.app',
    iosBundleId: 'com.example.projectUap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVAkZs8AhU_PWbT2jrYrUNHTarK4fT6Bg',
    appId: '1:369587275430:ios:e2cc9c713cbcde96931667',
    messagingSenderId: '369587275430',
    projectId: 'prak-mobile2025',
    databaseURL: 'https://prak-mobile2025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prak-mobile2025.firebasestorage.app',
    iosBundleId: 'com.example.projectUap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3ittMwwukoAo2gr8tKclmSeqyQd0VW0',
    appId: '1:369587275430:web:b8b87af499ecda78931667',
    messagingSenderId: '369587275430',
    projectId: 'prak-mobile2025',
    authDomain: 'prak-mobile2025.firebaseapp.com',
    databaseURL: 'https://prak-mobile2025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prak-mobile2025.firebasestorage.app',
    measurementId: 'G-HGZNYVNGBE',
  );

}