// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3Wj6AdvcJUrL2iC2ZAB_ML7Th0wq4G4',
    appId: '1:512307243514:web:77a447852f6ee91c6ddc43',
    messagingSenderId: '512307243514',
    projectId: 'lalapanbangajey',
    authDomain: 'lalapanbangajey.firebaseapp.com',
    storageBucket: 'lalapanbangajey.firebasestorage.app',
    measurementId: 'G-J15VXWR9MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmUlJMlJHcTNHSJuEZvTaaun9ou7ZEYo',
    appId: '1:512307243514:android:ee95ee71231b57026ddc43',
    messagingSenderId: '512307243514',
    projectId: 'lalapanbangajey',
    storageBucket: 'lalapanbangajey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlccgge7u-zBleanISCqrM-Rcx_C-9AI',
    appId: '1:512307243514:ios:1c04255c4e189cc16ddc43',
    messagingSenderId: '512307243514',
    projectId: 'lalapanbangajey',
    storageBucket: 'lalapanbangajey.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOlccgge7u-zBleanISCqrM-Rcx_C-9AI',
    appId: '1:512307243514:ios:1c04255c4e189cc16ddc43',
    messagingSenderId: '512307243514',
    projectId: 'lalapanbangajey',
    storageBucket: 'lalapanbangajey.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf3Wj6AdvcJUrL2iC2ZAB_ML7Th0wq4G4',
    appId: '1:512307243514:web:3e627f0c54e8d4b86ddc43',
    messagingSenderId: '512307243514',
    projectId: 'lalapanbangajey',
    authDomain: 'lalapanbangajey.firebaseapp.com',
    storageBucket: 'lalapanbangajey.firebasestorage.app',
    measurementId: 'G-CRBXMND6E6',
  );
}
